--Member Type
create table MEMBER_TYPE (NAME VARCHAR(20), MAX_LIVE_LOANS NUMERIC(3), MAX_OUTSTANDING_LIMIT DECIMAL(10, 2), ACTIVE BOOLEAN);

insert into MEMBER_TYPE (NAME, MAX_LIVE_LOANS, MAX_OUTSTANDING_LIMIT, ACTIVE) values ('Walk-In', null, null, true);
insert into MEMBER_TYPE (NAME, MAX_LIVE_LOANS, MAX_OUTSTANDING_LIMIT, ACTIVE) values ('Retailer Owner', 20, 200000, true);
insert into MEMBER_TYPE (NAME, MAX_LIVE_LOANS, MAX_OUTSTANDING_LIMIT, ACTIVE) values ('Employed', 20, 400000, true);
insert into MEMBER_TYPE (NAME, MAX_LIVE_LOANS, MAX_OUTSTANDING_LIMIT, ACTIVE) values ('Daily Vendor', 100, 100000, true);
insert into MEMBER_TYPE (NAME, MAX_LIVE_LOANS, MAX_OUTSTANDING_LIMIT, ACTIVE) values ('dummy', 100, 100000, false);
